#!/bin/bash
while getopts ":d:i:p:" opt; do
  case $opt in
    d) 
      copy_dir=$OPTARG
      cd "$copy_dir"
      echo "$PWD"
      ;;
    i) 
      argument=$OPTARG 
      ;;
    p)
      project=$OPTARG
      ;;
  esac
done

# Make sure project is something we recognize 
if [[ $project != 'TAP' && $project != "MAP" ]]; then
    error "Unrecognized project name "$project" - Use either MAP or TAP\n"
fi

if [[ -f $argument ]]; then
  echo "Input is a hashlist" ;
  hashlist="$argument"
else
  echo "Input is not a hashlist" 
  # Generate a sub list from the main Scans acquired hashlist using the sessions provided
  main_list=$(find /fs0/repos/tools/hash_lists/ -maxdepth 1 -type f -iname "*"$project"*ScansAcquired*.csv")
  head -n 1 "$main_list"  > subset.csv
  for i in $argument
    do
    cat $main_list | grep -e "$i" >> subset.csv # Grepping for session id 
    done
    hashlist=./subset.csv
fi
# Find out column numbers for sessions, map_ids and epoch 
sess_col=$(awk -v RS=',' '/session_id/{print NR; exit}' $hashlist)
epoch_col=$(awk -v RS=',' '/epoch/{print NR; exit}' $hashlist)
if [[ $project == 'MAP' ]]; then
    id_col=$(awk -v RS=',' '/map_id/{print NR; exit}' $hashlist)
elif [[ $project == 'TAP' ]]; then
    id_col=$(awk -v RS=',' '/vmac_id/{print NR; exit}' $hashlist)
fi

echo "$id_col"
tail -n +2 "$hashlist" | while read line 
do
sess=$(echo $line | awk -v s="$sess_col" -F ',' '{print $s}')
val=$(echo $line | awk -v m="$id_col" -F ',' '{print $m}')
epoch=$(echo $line | awk -v e="$epoch_col" -F ',' '{print $e}')

path=/fs0/"$project"/PROCESSED/"$val"/Brain/EPOCH"$epoch"/LST/"$sess"
echo "Removing _edit file for "$line""
rm "$copy_dir"/"$val"/b_000_lesion_lbm0_010_rm"$val"_"$sess"_"$epoch"_flair_edit.nii
echo "Renaming _edit_ltd to _edit for "$sess""
mv "$copy_dir"/"$val"/b_000_lesion_lbm0_010_rm"$val"_"$sess"_"$epoch"_flair_edit_ltd.nii "$copy_dir"/"$val"/b_000_lesion_lbm0_010_rm"$val"_"$sess"_"$epoch"_flair_edit.nii
mkdir -p "$path"/edits
echo "Copying edited files to /fs0 for "$sess""
cp "$copy_dir"/"$val"/b_000_lesion_lbm0_010_rm"$val"_"$sess"_"$epoch"_flair_edit.nii "$path"/edits
chmod 775 "$path"/edits/*
chmod -R 775 "$path"
done
